print ("Nama = Fatihah Asy Syifa")
print ("Nama Panggilan = Fatihah")
print ("NIM = I0322043")
print ("Alamat = Jati Kidul RT 01 RW 03, Bugel, Polokarto, Sukoharjo")
print ("=======================")
print ("Deskripsi Tempat Tinggal = Sukoharjo, disebut dengan Kota Jamu, Kota Tekstil, dan Kota Gamelan.")
print ("Julukan tersebut disematkan karena potensi yang dimiliki Kabupaten Sukoharjo.")
print ("Sukoharjo kaya akan potensi pada dunia perindustrian, baik itu tekstil maupun industri bidang seni seperti gamelan.")
print ("Hal itulah yang menjadikan Sukoharjo Makmur.")
print ("=======================")
print ("Harapan sebagai lulusan Teknik Industri = Dapat memajukan perindustrian di Indonesia dengan ikut andil dan berkontribusi sepenuhnya menuju suksesya industri 4.0")